name: Install and Test Elegant core
on: 
  push:
    paths:
      - source/**
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Speed up subsequent runs with caching
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # Install required deps for action
      - name: Install CLI Dependencies
        run: npm install

      # Install required deps for elegant framework subfolder
      - name: Install Elegant Package Dependencies
        run:  cd source/elegant && npm install --legacy-peer-deps

      # Finally, run our CI tests
      - name: Run the tests
        run: npm run test:ci

      # Build the code package
      - name: Build the core package
        run: npm run build:elegant